### ISSUE TITLE
rMATs error in Conda environment

### ISSUE THREAD

**Issue by sr8510** [Xinglab/rmats-turbo#131]
Hello. I created a conda environment and installed rmats using this code: conda install -c conda-forge -c bioconda rmats=4.1.1
I check which rmats and which python and I got both to be in the same location.
However, when I run rmats I got this error:
rmats.py --b1 Cont.txt --b2 As.txt --gtf gencode.gtf --readLength 151 --od ./cont-As --tmp ./tmp
Traceback (most recent call last):
  File "/home/sherif/anaconda3/envs/rmats/bin/rmats.py", line 536, in <module>
    main()
  File "/home/sherif/anaconda3/envs/rmats/bin/rmats.py", line 502, in main
    args = get_args()
  File "/home/sherif/anaconda3/envs/rmats/bin/rmats.py", line 194, in get_args
    args.prep_prefix = claim_prep_prefix(args.task, args.tmp)
  File "/home/sherif/anaconda3/envs/rmats/bin/rmats.py", line 482, in claim_prep_prefix
    with open(file_path, 'wt'):
OSError: [Errno 71] Protocol error: './tmp/2021-06-21-13:10:08_344538_0.rmats'

What might be the issue here and how to fix it?

**Comment by EricKutschera** [comment]
This is the line from the stack trace: https://github.com/Xinglab/rmats-turbo/blob/v4.1.1/rMATS_pipeline/rmatspipeline/rmatspipeline.pyx#L3444

It's trying to interpret the string it read from your --b1/--b2 file but finds a non-ascii character: UnicodeEncodeError: 'ascii' codec can't encode character '\ufeff' in position 0: ordinal not in range(128)

\ufeff is the Byte Order Mark (BOM): https://unicode-table.com/en/FEFF/ https://en.wikipedia.org/wiki/Byte_order_mark which is used for unicode files

You should be able to update your --b1/--b2 files to be ascii encoded to resolve the error
