### ISSUE TITLE
Error: No module named rmatspipeline

### ISSUE THREAD

**Issue by groy87** [Xinglab/rmats-turbo#165]
I installed conda using `conda install -c bioconda rmats`
but when I run rmats.py, it shows an error:

`python rmats_turbo_v4_1_1/rmats.py --b1 /home/groy/data/rMATS-turbo/BAM_input_files/SW_24h.txt --b2 /home/groy/data/rMATS-turbo/BAM_input_files/DMSO_24h.txt --gtf /home/groy/data/gencode.vM27.primary_assembly.annotation.gtf -t paired --readLength 100 --variable-read-length --nthread 4 --od /home/groy/data/rMATS-turbo/output/SW_24h_vs_DMSO_24h --tmp /home/groy/data/rMATS-turbo/tmp_output
Traceback (most recent call last):
  File "rmats_turbo_v4_1_1/rmats.py", line 19, in <module>
    from rmatspipeline import run_pipe
ImportError: No module named rmatspipeline`

(The version of python is 2.7.16)

**Comment by EricKutschera** [comment]
Do the suggestions in this post work for you?
https://github.com/Xinglab/rmats-turbo/issues/67

**Comment by groy87** [comment]
Yes, I tried the solutions given in #67 and the paths for rmats.py and python are same

```
which python
/opt/miniconda3/bin/python
```
`which rmats.py
/opt/miniconda3/bin/rmats.py`

Not sure what to do next.

**Comment by EricKutschera** [comment]
In your first post, the command started with `python rmats_turbo_v4_1_1/rmats.py`. Based on the `which` results I think that will translate to `/opt/miniconda3/bin/python rmats_turbo_v4_1_1/rmats.py`. But it seems like the rmats.py you installed from conda ended up at `/opt/miniconda3/bin/rmats.py`. I think this command might work: `/opt/miniconda3/bin/python /opt/miniconda3/bin/rmats.py`

That way the conda installed python is used with the conda installed rmats.py

**Comment by groy87** [comment]
If I use `/opt/miniconda3/bin/python /opt/miniconda3/bin/rmats.py`
I get another error:
![image](https://user-images.githubusercontent.com/94996583/144311003-2cf2db96-6bcc-4cf3-a412-03c42d809c8f.png)

**Comment by EricKutschera** [comment]
That command is just python and the rmats script, but rmats.py also requires arguments like the `--b1` you had in your original post

**Comment by groy87** [comment]
Sorry for that mistake.

But why does it say unrecognized arguments for the `--tmp` argument ?
same error for the `--variable-read-length` argument too.

![image](https://user-images.githubusercontent.com/94996583/144313011-a8bc1063-0114-4c04-b07b-43e8faeebc2d.png)

**Comment by EricKutschera** [comment]
My guess is that the conda install picked an old version since no specific version was requested. You could try installing with `conda install -c conda-forge -c bioconda rmats=4.1.1`

**Comment by groy87** [comment]
After installing with `install -c conda-forge -c bioconda rmats=4.1.1`, I still have the same error.

![image](https://user-images.githubusercontent.com/94996583/145288044-17ad9ae7-4da0-425f-b071-4a7c405a560c.png)

Although at the end of installation, I got the following message. Not sure if this has anything to do with the error.
![image](https://user-images.githubusercontent.com/94996583/145288314-45a27519-9589-4226-a4fd-7cb1097ab2f7.png)

**Comment by EricKutschera** [comment]
Because of the error "Package bcftools conflicts for: ...", 4.1.1 was not installed. The error is saying that at least one dependency for rmats=4.1.1 conflicts with something else you have installed in your conda environment

You can make a new conda environment that just has rmats and then there should be no dependency conflict:
```
conda create --prefix /path/to/install/new/conda/environment
conda activate /path/to/install/new/conda/environment
conda install -c conda-forge -c bioconda rmats=4.1.1
```

After the install, as long as the conda environment is activated you should be able to use rmats with just `rmats.py`. Or without activating the environment `/path/to/install/new/conda/environment/bin/python /path/to/install/new/conda/environment/bin/rmats.py`

**Comment by groy87** [comment]
Thank you!!! After creating the conda environment, it worked.
Another question: If I use a different gtf file than what was used with STAR, is that a problem?

Like **UCSC refseq mm10** during STAR alignment versus **UCSC refseq mm39** OR **Gencode vM27** with rMATS?

**Comment by EricKutschera** [comment]
rMATS matches up the coordinates from the aligned reads with the transcripts from the gtf to detect and count splicing events. Ideally you would use the same gtf for alignment and running rMATS so that the coordinates match up. It is possible to use a different gtf as long as the coordinates are consistent. If the gtf files do not match up, then I would expect to see a lot of EXON_NOT_MATCHED_TO_ANNOTATION and JUNCTION_NOT_MATCHED_TO_ANNOTATION in the output which indicate the aligned reads could not be matched to the coordinates in the gtf

**Comment by EricKutschera** [comment]
It looks like this is the main error in that output:
`Collecting package metadata (repodata.json): failed`

The url it mentioned worked for me just now: `curl -L https://mirrors.ustc.edu.cn/anaconda/cloud/conda-forge/noarch/repodata.json -O`

The error also says `HTTP errors are often intermittent, and a simple retry will get you on your way`

Maybe you could try again now to see if it is resolved?

I was able to install rmats just now with:
```
conda create --prefix /path/to/install/new/conda/environment
conda activate /path/to/install/new/conda/environment
conda install -c conda-forge -c bioconda rmats=4.1.2
```

**Comment by LonglongaaaGo** [comment]
@EricKutschera Hi Eric,
Thank you so much!
It works well! It starts to download rmats packages.
But when I use the pip list, I cannot show these packages.

-----
(rmats) k@1k:~/Workspace/rmats-turbo-master$ pip list
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
certifi (2016.9.26)
numpy (1.19.5)
pip (9.0.1)
setuptools (36.4.0)
wheel (0.29.0)
You are using pip version 9.0.1, however version 22.2.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
--------

Moreover, when I run 
python rmats.py
-- It still cannot find the 'rmatspipeline'
Traceback (most recent call last):
  File "rmats.py", line 19, in <module>
    from rmatspipeline import run_pipe
ModuleNotFoundError: No module named 'rmatspipeline'
--
Thank you so much for your help!

**Comment by lironghu** [comment]
Hi Eric, 

I also got this issue. I am just wondering  whether we have to  set the same path for rmats with python?

I already tried the way of fixing the path.
