### ISSUE TITLE
cannot open bam file created by hisat2 (not using "~")

### ISSUE THREAD

**Issue by ianlee96** [Xinglab/rmats-turbo#191]
when i type this
`python /home/ianlee/biotools/rmats_turbo_v4_1_2/rmats.py --b1 /mnt/c/SCIProgram/trans/04rMATS/list/04LrG.txt --b2 /mnt/c/SCIProgram/trans/04rMATS/list/04LrR.txt --gtf /mnt/c/SCIProgram/genome/Lb/Lbfix.gtf -t paired --readLength 50 --nthread 11 --od /mnt/c/SCIProgram/trans/04rMATS/output --tmp /mnt/c/SCIProgram/trans/04rMATS/tmp_output --novelSS`
rMATS returned this
```
gtf: 0.9844145774841309
There are 33431 distinct gene ID in the gtf file
There are 33432 distinct transcript ID in the gtf file
There are 33430 one-transcript genes in the gtf file
There are 174723 exons in the gtf file
There are 4833 one-exon transcripts in the gtf file
There are 4833 one-transcript genes with only one exon in the transcript
Average number of transcripts per gene is 1.000030
Average number of exons per transcript is 5.226220
Average number of exons per transcript excluding one-exon tx is 5.940417
Average number of gene per geneGroup is 1.978729
statistic: 0.012811422348022461
Fail to open /mnt/c/SCIProgram/trans/02hisat2/hisat2_output/LrG1.bam
/mnt/c/SCIProgram/trans/02hisat2/hisat2_output/LrG2.bam
/mnt/c/SCIProgram/trans/02hisat2/hisat2_output/LrG3.bam
Fail to open /mnt/c/SCIProgram/trans/02hisat2/hisat2_output/LrR1.bam
/mnt/c/SCIProgram/trans/02hisat2/hisat2_output/LrR2.bam
/mnt/c/SCIProgram/trans/02hisat2/hisat2_output/LrR3.bam

read outcome totals across all BAMs
USED: 0
NOT_PAIRED: 0
NOT_NH_1: 0
NOT_EXPECTED_CIGAR: 0
NOT_EXPECTED_READ_LENGTH: 0
NOT_EXPECTED_STRAND: 0
EXON_NOT_MATCHED_TO_ANNOTATION: 0
JUNCTION_NOT_MATCHED_TO_ANNOTATION: 0
CLIPPED: 0
total: 0
outcomes by BAM written to: /mnt/c/SCIProgram/trans/04rMATS/tmp_output/2022-04-10-11_18_34_323169_read_outcomes_by_bam.txt

novel: 0.005591869354248047
The splicing graph and candidate read have been saved into /mnt/c/SCIProgram/trans/04rMATS/tmp_output/2022-04-10-11_18_34_323169_*.rmats
save: 0.004040718078613281
Traceback (most recent call last):
  File "/home/ianlee/biotools/rmats_turbo_v4_1_2/rmats.py", line 595, in <module>
    main()
  File "/home/ianlee/biotools/rmats_turbo_v4_1_2/rmats.py", line 563, in main
    run_pipe(args)
  File "rmatspipeline/rmatspipeline.pyx", line 3860, in rmats.rmatspipeline.run_pipe
  File "rmatspipeline/rmatspipeline.pyx", line 3723, in rmats.rmatspipeline.split_sg_files_by_bam
  File "rmatspipeline/rmatspipeline.pyx", line 3731, in rmats.rmatspipeline.split_sg_files_by_bam
ValueError: invalid literal for int() with base 10: '/mnt/c/SCIProgram/trans/02hisat2/hisat2_output/LrG2.bam'
```
this is my bam list file 04LrG:
```
/mnt/c/SCIProgram/trans/02hisat2/hisat2_output/LrG1.bam
/mnt/c/SCIProgram/trans/02hisat2/hisat2_output/LrG2.bam
/mnt/c/SCIProgram/trans/02hisat2/hisat2_output/LrG3.bam
```
04LrR is similar as 04LrG
and my bam file is in this dir
`/mnt/c/SCIProgram/trans/02hisat2/hisat2_output$ ls`
ubuntu returned
```
LbG1.bam      LbG3.bam.bai  LbR3.bam      LbT2.bam.bai  LrG1.bam.bai  LrR1.bam      LrR3.bam.bai  LrT3.bam
LbG1.bam.bai  LbR1.bam      LbR3.bam.bai  LbT3.bam      LrG2.bam      LrR1.bam.bai  LrT1.bam      LrT3.bam.bai
LbG2.bam      LbR1.bam.bai  LbT1.bam      LbT3.bam.bai  LrG2.bam.bai  LrR2.bam      LrT1.bam.bai  hisat2.sh
LbG2.bam.bai  LbR2.bam      LbT1.bam.bai  Lbfix.exon    LrG3.bam      LrR2.bam.bai  LrT2.bam      hisat21.sh
LbG3.bam      LbR2.bam.bai  LbT2.bam      LrG1.bam      LrG3.bam.bai  LrR3.bam      LrT2.bam.bai  stringtie.sh
```
 i did not use `~` to instead `/home/${username}`
could you tell me what's wrong with the code, so that i can continue analysis?

**Comment by EricKutschera** [comment]
I think your --b1 file should use commas instead of newlines:
```
/mnt/c/SCIProgram/trans/02hisat2/hisat2_output/LrG1.bam,/mnt/c/SCIProgram/trans/02hisat2/hisat2_output/LrG2.bam,/mnt/c/SCIProgram/trans/02hisat2/hisat2_output/LrG3.bam
```

The output shows:
```
Fail to open /mnt/c/SCIProgram/trans/02hisat2/hisat2_output/LrG1.bam
/mnt/c/SCIProgram/trans/02hisat2/hisat2_output/LrG2.bam
/mnt/c/SCIProgram/trans/02hisat2/hisat2_output/LrG3.bam
Fail to open /mnt/c/SCIProgram/trans/02hisat2/hisat2_output/LrR1.bam
/mnt/c/SCIProgram/trans/02hisat2/hisat2_output/LrR2.bam
/mnt/c/SCIProgram/trans/02hisat2/hisat2_output/LrR3.bam
```
rMATS will print "Fail to open" once for each bam it tries to open. https://github.com/Xinglab/rmats-turbo/blob/v4.1.2/rMATS_pipeline/rmatspipeline/rmatspipeline.pyx#L783
In the output, "Fail to open" is only printed twice which could happen if the paths to the 3 bams in the --b1 file are not formatted as expected.

From the help message for --b1: https://github.com/Xinglab/rmats-turbo/tree/v4.1.2#all-arguments
```
--b1 B1               A text file containing a comma separated list of the
                        BAM files for sample_1. (Only if using BAM)
```

**Comment by ianlee96** [comment]
thank you！
