### ISSUE TITLE
Error in rmats run

### ISSUE THREAD

**Issue by ShenTTT** [Xinglab/rmats-turbo#199]
Hi,

I tried to install rmats through bioconda;
```
conda install --name rmats -c bioconda rmats=4.1.2
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /home/butterflylab/miniconda3/envs/rmats

  added / updated specs:
    - rmats=4.1.2


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    blas-2.106                 |         openblas          12 KB  conda-forge
    libblas-3.9.0              |       6_openblas          11 KB  conda-forge
    libcblas-3.9.0             |       6_openblas          11 KB  conda-forge
    liblapack-3.9.0            |       6_openblas          11 KB  conda-forge
    liblapacke-3.9.0           |       6_openblas          11 KB  conda-forge
    libopenblas-0.3.12         |pthreads_h4812303_1         8.9 MB  conda-forge
    numpy-1.21.5               |   py39h7a5d4dd_2          10 KB
    numpy-base-1.21.5          |   py39hb8be1f0_2         4.9 MB
    python-3.9.7               |       h12debd9_1        18.6 MB
    setuptools-61.2.0          |   py39h06a4308_0        1011 KB
    xz-5.2.5                   |       h7f8727e_1         339 KB
    ------------------------------------------------------------
                                           Total:        33.8 MB

The following NEW packages will be INSTALLED:

  _libgcc_mutex      conda-forge/linux-64::_libgcc_mutex-0.1-conda_forge
  _openmp_mutex      conda-forge/linux-64::_openmp_mutex-4.5-2_kmp_llvm
  blas               conda-forge/linux-64::blas-2.106-openblas
  ca-certificates    pkgs/main/linux-64::ca-certificates-2022.4.26-h06a4308_0
  certifi            pkgs/main/linux-64::certifi-2021.10.8-py39h06a4308_2
  gsl                pkgs/main/linux-64::gsl-2.7.1-hd82f3ee_0
  ld_impl_linux-64   pkgs/main/linux-64::ld_impl_linux-64-2.35.1-h7274673_9
  libblas            conda-forge/linux-64::libblas-3.9.0-6_openblas
  libcblas           conda-forge/linux-64::libcblas-3.9.0-6_openblas
  libffi             pkgs/main/linux-64::libffi-3.3-he6710b0_2
  libgcc-ng          conda-forge/linux-64::libgcc-ng-11.2.0-h1d223b6_16
  libgfortran-ng     conda-forge/linux-64::libgfortran-ng-11.2.0-h69a702a_16
  libgfortran5       conda-forge/linux-64::libgfortran5-11.2.0-h5c6108e_16
  liblapack          conda-forge/linux-64::liblapack-3.9.0-6_openblas
  liblapacke         conda-forge/linux-64::liblapacke-3.9.0-6_openblas
  libopenblas        conda-forge/linux-64::libopenblas-0.3.12-pthreads_h4812303_1
  libstdcxx-ng       conda-forge/linux-64::libstdcxx-ng-11.2.0-he4da1e4_16
  libzlib            conda-forge/linux-64::libzlib-1.2.11-h166bdaf_1014
  llvm-openmp        conda-forge/linux-64::llvm-openmp-14.0.3-he0ac6c6_0
  ncurses            pkgs/main/linux-64::ncurses-6.3-h7f8727e_2
  numpy              pkgs/main/linux-64::numpy-1.21.5-py39h7a5d4dd_2
  numpy-base         pkgs/main/linux-64::numpy-base-1.21.5-py39hb8be1f0_2
  openssl            pkgs/main/linux-64::openssl-1.1.1n-h7f8727e_0
  pip                pkgs/main/linux-64::pip-21.2.4-py39h06a4308_0
  python             pkgs/main/linux-64::python-3.9.7-h12debd9_1
  python_abi         conda-forge/linux-64::python_abi-3.9-2_cp39
  readline           pkgs/main/linux-64::readline-8.1.2-h7f8727e_1
  rmats              bioconda/linux-64::rmats-4.1.2-py39hd863d43_3
  setuptools         pkgs/main/linux-64::setuptools-61.2.0-py39h06a4308_0
  sqlite             pkgs/main/linux-64::sqlite-3.36.0-hc218d9a_0
  star               bioconda/linux-64::star-2.7.10a-h9ee0642_0
  tk                 pkgs/main/linux-64::tk-8.6.11-h1ccaba5_0
  tzdata             pkgs/main/noarch::tzdata-2022a-hda174b7_0
  wheel              pkgs/main/noarch::wheel-0.37.1-pyhd3eb1b0_0
  xz                 pkgs/main/linux-64::xz-5.2.5-h7f8727e_1
  zlib               conda-forge/linux-64::zlib-1.2.11-h166bdaf_1014


Proceed ([y]/n)? y


Downloading and Extracting Packages
libblas-3.9.0        | 11 KB     | ##################################################################### | 100% 
setuptools-61.2.0    | 1011 KB   | ##################################################################### | 100% 
python-3.9.7         | 18.6 MB   | ##################################################################### | 100% 
libcblas-3.9.0       | 11 KB     | ##################################################################### | 100% 
numpy-base-1.21.5    | 4.9 MB    | ##################################################################### | 100% 
numpy-1.21.5         | 10 KB     | ##################################################################### | 100% 
libopenblas-0.3.12   | 8.9 MB    | ##################################################################### | 100% 
liblapack-3.9.0      | 11 KB     | ##################################################################### | 100% 
xz-5.2.5             | 339 KB    | ##################################################################### | 100% 
blas-2.106           | 12 KB     | ##################################################################### | 100% 
liblapacke-3.9.0     | 11 KB     | ##################################################################### | 100% 
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
```
Then I activated the env;
`conda activate rmats`
And then ran rmats;
```
python '/home/butterflylab/miniconda3/envs/rmats/bin/rmats.py'  --b1 '/media/butterflylab/Shen/larval_eyespot/splicing/rmats/test/b1.txt' --b2 '/media/butterflylab/Shen/larval_eyespot/splicing/rmats/test/b2.txt' --gtf '/media/butterflylab/Shen/genome_data/converted.gtf' -t paired --readLength 150 --variable-read-length  --nthread 32 --od '/media/butterflylab/Shen/larval_eyespot/splicing/rmats/test/out' --tmp '/media/butterflylab/Shen/larval_eyespot/splicing/rmats/test/tmp'
gtf: 1.8067727088928223
There are 15845 distinct gene ID in the gtf file
There are 23362 distinct transcript ID in the gtf file
There are 12345 one-transcript genes in the gtf file
There are 196681 exons in the gtf file
There are 1916 one-exon transcripts in the gtf file
There are 1908 one-transcript genes with only one exon in the transcript
Average number of transcripts per gene is 1.474408
Average number of exons per transcript is 8.418843
Average number of exons per transcript excluding one-exon tx is 9.081647
Average number of gene per geneGroup is 60.550649
statistic: 0.002075672149658203

read outcome totals across all BAMs
USED: 132724231
NOT_PAIRED: 14637
NOT_NH_1: 0
NOT_EXPECTED_CIGAR: 22441859
NOT_EXPECTED_READ_LENGTH: 0
NOT_EXPECTED_STRAND: 0
EXON_NOT_MATCHED_TO_ANNOTATION: 33985146
JUNCTION_NOT_MATCHED_TO_ANNOTATION: 1780224
CLIPPED: 60676305
total: 251622402
outcomes by BAM written to: /media/butterflylab/Shen/larval_eyespot/splicing/rmats/test/tmp/2022-05-06-10_19_21_933617_read_outcomes_by_bam.txt

novel: 1533.0726299285889
The splicing graph and candidate read have been saved into /media/butterflylab/Shen/larval_eyespot/splicing/rmats/test/tmp/2022-05-06-10_19_21_933617_*.rmats
save: 1.041212558746338
loadsg: 0.02333831787109375

==========
Done processing each gene from dictionary to compile AS events
Found 6092 exon skipping events
Found 872 exon MX events
Found 2022 alt SS events
There are 1130 alt 3 SS events and 892 alt 5 SS events.
Found 192 RI events
==========

ase: 0.17022418975830078
count: 1.7350285053253174
Processing count files.
/home/butterflylab/miniconda3/envs/rmats/rMATS/rMATS_C/rMATSexe: error while loading shared libraries: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/home/butterflylab/miniconda3/envs/rmats/rMATS/rMATS_P/FDR.py", line 53, in <module>
    ifile=open(sys.argv[1]);title=ifile.readline();
FileNotFoundError: [Errno 2] No such file or directory: '/media/butterflylab/Shen/larval_eyespot/splicing/rmats/test/out/tmp/JC_SE/rMATS_result_P-V.txt'
paste: /media/butterflylab/Shen/larval_eyespot/splicing/rmats/test/out/tmp/JC_SE/rMATS_result_FDR.txt: No such file or directory
/home/butterflylab/miniconda3/envs/rmats/rMATS/rMATS_C/rMATSexe: error while loading shared libraries: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/home/butterflylab/miniconda3/envs/rmats/rMATS/rMATS_P/FDR.py", line 53, in <module>
    ifile=open(sys.argv[1]);title=ifile.readline();
FileNotFoundError: [Errno 2] No such file or directory: '/media/butterflylab/Shen/larval_eyespot/splicing/rmats/test/out/tmp/JCEC_SE/rMATS_result_P-V.txt'
paste: /media/butterflylab/Shen/larval_eyespot/splicing/rmats/test/out/tmp/JCEC_SE/rMATS_result_FDR.txt: No such file or directory
/home/butterflylab/miniconda3/envs/rmats/rMATS/rMATS_C/rMATSexe: error while loading shared libraries: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/home/butterflylab/miniconda3/envs/rmats/rMATS/rMATS_P/FDR.py", line 53, in <module>
    ifile=open(sys.argv[1]);title=ifile.readline();
FileNotFoundError: [Errno 2] No such file or directory: '/media/butterflylab/Shen/larval_eyespot/splicing/rmats/test/out/tmp/JC_MXE/rMATS_result_P-V.txt'
paste: /media/butterflylab/Shen/larval_eyespot/splicing/rmats/test/out/tmp/JC_MXE/rMATS_result_FDR.txt: No such file or directory
/home/butterflylab/miniconda3/envs/rmats/rMATS/rMATS_C/rMATSexe: error while loading shared libraries: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/home/butterflylab/miniconda3/envs/rmats/rMATS/rMATS_P/FDR.py", line 53, in <module>
    ifile=open(sys.argv[1]);title=ifile.readline();
FileNotFoundError: [Errno 2] No such file or directory: '/media/butterflylab/Shen/larval_eyespot/splicing/rmats/test/out/tmp/JCEC_MXE/rMATS_result_P-V.txt'
paste: /media/butterflylab/Shen/larval_eyespot/splicing/rmats/test/out/tmp/JCEC_MXE/rMATS_result_FDR.txt: No such file or directory
/home/butterflylab/miniconda3/envs/rmats/rMATS/rMATS_C/rMATSexe: error while loading shared libraries: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/home/butterflylab/miniconda3/envs/rmats/rMATS/rMATS_P/FDR.py", line 53, in <module>
    ifile=open(sys.argv[1]);title=ifile.readline();
FileNotFoundError: [Errno 2] No such file or directory: '/media/butterflylab/Shen/larval_eyespot/splicing/rmats/test/out/tmp/JC_A3SS/rMATS_result_P-V.txt'
paste: /media/butterflylab/Shen/larval_eyespot/splicing/rmats/test/out/tmp/JC_A3SS/rMATS_result_FDR.txt: No such file or directory
/home/butterflylab/miniconda3/envs/rmats/rMATS/rMATS_C/rMATSexe: error while loading shared libraries: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/home/butterflylab/miniconda3/envs/rmats/rMATS/rMATS_P/FDR.py", line 53, in <module>
    ifile=open(sys.argv[1]);title=ifile.readline();
FileNotFoundError: [Errno 2] No such file or directory: '/media/butterflylab/Shen/larval_eyespot/splicing/rmats/test/out/tmp/JCEC_A3SS/rMATS_result_P-V.txt'
paste: /media/butterflylab/Shen/larval_eyespot/splicing/rmats/test/out/tmp/JCEC_A3SS/rMATS_result_FDR.txt: No such file or directory
/home/butterflylab/miniconda3/envs/rmats/rMATS/rMATS_C/rMATSexe: error while loading shared libraries: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/home/butterflylab/miniconda3/envs/rmats/rMATS/rMATS_P/FDR.py", line 53, in <module>
    ifile=open(sys.argv[1]);title=ifile.readline();
FileNotFoundError: [Errno 2] No such file or directory: '/media/butterflylab/Shen/larval_eyespot/splicing/rmats/test/out/tmp/JC_A5SS/rMATS_result_P-V.txt'
paste: /media/butterflylab/Shen/larval_eyespot/splicing/rmats/test/out/tmp/JC_A5SS/rMATS_result_FDR.txt: No such file or directory
/home/butterflylab/miniconda3/envs/rmats/rMATS/rMATS_C/rMATSexe: error while loading shared libraries: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/home/butterflylab/miniconda3/envs/rmats/rMATS/rMATS_P/FDR.py", line 53, in <module>
    ifile=open(sys.argv[1]);title=ifile.readline();
FileNotFoundError: [Errno 2] No such file or directory: '/media/butterflylab/Shen/larval_eyespot/splicing/rmats/test/out/tmp/JCEC_A5SS/rMATS_result_P-V.txt'
paste: /media/butterflylab/Shen/larval_eyespot/splicing/rmats/test/out/tmp/JCEC_A5SS/rMATS_result_FDR.txt: No such file or directory
/home/butterflylab/miniconda3/envs/rmats/rMATS/rMATS_C/rMATSexe: error while loading shared libraries: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/home/butterflylab/miniconda3/envs/rmats/rMATS/rMATS_P/FDR.py", line 53, in <module>
    ifile=open(sys.argv[1]);title=ifile.readline();
FileNotFoundError: [Errno 2] No such file or directory: '/media/butterflylab/Shen/larval_eyespot/splicing/rmats/test/out/tmp/JC_RI/rMATS_result_P-V.txt'
paste: /media/butterflylab/Shen/larval_eyespot/splicing/rmats/test/out/tmp/JC_RI/rMATS_result_FDR.txt: No such file or directory
/home/butterflylab/miniconda3/envs/rmats/rMATS/rMATS_C/rMATSexe: error while loading shared libraries: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/home/butterflylab/miniconda3/envs/rmats/rMATS/rMATS_P/FDR.py", line 53, in <module>
    ifile=open(sys.argv[1]);title=ifile.readline();
FileNotFoundError: [Errno 2] No such file or directory: '/media/butterflylab/Shen/larval_eyespot/splicing/rmats/test/out/tmp/JCEC_RI/rMATS_result_P-V.txt'
paste: /media/butterflylab/Shen/larval_eyespot/splicing/rmats/test/out/tmp/JCEC_RI/rMATS_result_FDR.txt: No such file or directory
Done processing count files.

```
It seems that there are still some dependencies that are not compatible, how do I fix this?

Thanks!

**Comment by ShenTTT** [comment]
Hi Eric,

Thank you for your help! I reinstalled and it worked for me.
