### ISSUE TITLE
FileNotFoundError in conda environment

### ISSUE THREAD

**Issue by Eureka199612** [Xinglab/rmats-turbo#203]
HI,
I installed rMats through conda with these codes:

conda create -n  rmats python==3.6.12
conda activate rmats
conda install -c bioconda rmats=4.1.2

Then, enter bin,
python rmats.py --b1 /home/eureka/Desktop/bam/CTR.txt --b2 /home/eureka/Desktop/bam/HRVA.txt --gtf /home/eureka/Desktop/bam/Homo_sapiens.GRCh38.86.gtf -t paired --readLength 50 --nthread 4 --od /home/eureka/Desktop/bam/AS_events --tmp /home/eureka/Desktop/bam/tmp_output --paired-stats

However, after I run the code, I got an error like this:
**FileNotFoundError: [Errno 2] No such file or directory: 'Rscript'**

output files：
[AS_Event].MATS.JC.txt and [AS_Event].MATS.JCEC.txt
are missing

read outcome totals across all BAMs
USED: 31273
NOT_PAIRED: 44099435
NOT_NH_1: 26621245
NOT_EXPECTED_CIGAR: 3478038
NOT_EXPECTED_READ_LENGTH: 279286553
NOT_EXPECTED_STRAND: 0
EXON_NOT_MATCHED_TO_ANNOTATION: 615
JUNCTION_NOT_MATCHED_TO_ANNOTATION: 145
CLIPPED: 18472872
total: 371990176
outcomes by BAM written to: /home/eureka/Desktop/bam/tmp_output/2022-05-29-14_51_10_487788_read_outcomes_by_bam.txt

novel: 450.8390510082245
he splicing graph and candidate read have been saved into /home/eureka/Desktop/bam/tmp_output/2022-05-29-14_51_10_487788_*.rmats
save: 0.022398948669433594 
loadsg: 0.000728607177734375

Done processing each gene from dictionary to compile AS events
Found 39164 exon skipping events
Found 2156 exon MX events
Found 13072 alt SS events
There are 8016 alt 3 SS events and 5056 alt 5 SS events.
Found 5746 RI events

ase: 1.5489015579223633
count: 0.43913960456848145
Processing count files.
Traceback (most recent call last):
  File "/home/eureka/miniconda3/envs/rmats/bin/rmats.py", line 595, in <module>
    main()
  File "/home/eureka/miniconda3/envs/rmats/bin/rmats.py", line 581, in main
    process_counts(jc_it % (event_type), args.tstat, 'JC', event_type,
  File "/home/eureka/miniconda3/envs/rmats/bin/rmats.py", line 420, in process_counts
    paired_model_return_code = subprocess.call(
  File "/home/eureka/miniconda3/envs/rmats/lib/python3.9/subprocess.py", line 349, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/home/eureka/miniconda3/envs/rmats/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/home/eureka/miniconda3/envs/rmats/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'Rscript'

(my operating system is: Ubuntu 20.04.4 LTS)

**Comment by EricKutschera** [comment]
For the conda environment, I needed to use `-c conda-forge` to get rmats installed, but your conda may be configured to use conda-forge automatically. Here are the commands I used
```
conda create --prefix ./conda_env
conda activate ./conda_env
conda install -c conda-forge -c bioconda python=3.6.12 rmats=4.1.2
```
I then got a similar error as you because running rmats with --paired-stats will try to run PAIRADISE which is written in R and not park of the rmats conda package:
https://github.com/Xinglab/rmats-turbo/blob/v4.1.2/rmats.py#L417
https://github.com/Xinglab/rmats-turbo/blob/v4.1.2/rMATS_R/paired_model.R#L1

The version of PAIRADISE that rmats uses is not available through conda and needs to be installed separately. The `build_rmats` script includes some code to install it, but if you already have a working install of rmats 4.1.2 with a conda environment that is activated you can download this file (https://github.com/Xinglab/rmats-turbo/blob/v4.1.2/install_r_deps.R) and then run:
```
conda install -c conda-forge -c bioconda r-base=3.6.3
git clone https://github.com/Xinglab/PAIRADISE.git
Rscript install_r_deps.R
```

Then if you retry the rmats.py command, that error about Rscript should not happen anymore

As a separate issue, from the read outcome totals there were `USED: 31273` and `NOT_EXPECTED_READ_LENGTH: 279286553` out of `total: 371990176`. You could try a different `--readLength` or use `--variable-read-length`
