### ISSUE TITLE
 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte

### ISSUE THREAD

**Issue by zhou-lei5** [Xinglab/rmats-turbo#213]
File "/xtdisk/liuzq_group/zhoulei/software/conda3/envs/rmats/lib/python3.9/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte

hello,I have no idea about this problem.How can i solve it

**Comment by zhou-lei5** [comment]
and the version of rMATS is 4.1.2 ,built by conda.

**Comment by zhou-lei5** [comment]
Traceback (most recent call last):
  File "/xtdisk/liuzq_group/zhoulei/software/conda3/envs/rmats/bin/rmats.py", line 595, in <module>
    main()
  File "/xtdisk/liuzq_group/zhoulei/software/conda3/envs/rmats/bin/rmats.py", line 558, in main
    args = get_args()
  File "/xtdisk/liuzq_group/zhoulei/software/conda3/envs/rmats/bin/rmats.py", line 188, in get_args
    args.b1 = fp.read().strip().strip(',')
  File "/xtdisk/liuzq_group/zhoulei/software/conda3/envs/rmats/lib/python3.9/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte

**Comment by zhou-lei5** [comment]
Thanks,Eric.
I got it.I found out that my input was separated by newlines, instead of commas.
