### ISSUE TITLE
Error running rmats.py 

### ISSUE THREAD

**Issue by mmaslon** [Xinglab/rmats-turbo#262]
I completed the analysis using the following command:

python3 rmats.py --b1 /Users/magdamaslon/Documents/Magdypliki/rMATSdata/HEK293T_con_bams.txt --b2 /Users/magdamaslon/Documents/Magdypliki/rMATSdata/HEK293T_mut_bams.txt --gtf /Users/magdamaslon/Documents/Magdypliki/rMATSdata/Homo_sapiens.GRCh38.109.gtf -t paired --readLength 125 --libType fr—-firststrand nthread 1 --od /Users/magdamaslon/Documents/Magdypliki/rMATSdata/output --tmp /Users/magdamaslon/Documents/Magdypliki/rMATSdata/tmp

The stdout was looking fine until the last few lines: Accordingly, no summary..txt file has been generated. Plesae see the screenshot of generated files below.

gtf: 29.454493045806885
There are 62710 distinct gene ID in the gtf file
There are 252798 distinct transcript ID in the gtf file
There are 38690 one-transcript genes in the gtf file
There are 1648278 exons in the gtf file
There are 26167 one-exon transcripts in the gtf file
There are 23367 one-transcript genes with only one exon in the transcript
Average number of transcripts per gene is 4.031223
Average number of exons per transcript is 6.520139
Average number of exons per transcript excluding one-exon tx is 7.157498
Average number of gene per geneGroup is 8.658191
statistic: 0.026113033294677734

read outcome totals across all BAMs
USED: 304937392
NOT_PAIRED: 0
NOT_NH_1: 71813876
NOT_EXPECTED_CIGAR: 3965715
NOT_EXPECTED_READ_LENGTH: 0
NOT_EXPECTED_STRAND: 0
EXON_NOT_MATCHED_TO_ANNOTATION: 10524760
JUNCTION_NOT_MATCHED_TO_ANNOTATION: 635267
CLIPPED: 0
total: 391877010
outcomes by BAM written to: /Users/magdamaslon/Documents/Magdypliki/rMATSdata/tmp/2023-02-28-11_36_25_588516_read_outcomes_by_bam.txt

novel: 1628.0768220424652
The splicing graph and candidate read have been saved into /Users/magdamaslon/Documents/Magdypliki/rMATSdata/tmp/2023-02-28-11_36_25_588516_*.rmats
save: 11.559301137924194
loadsg: 0.388258695602417

==========
Done processing each gene from dictionary to compile AS events
Found 110717 exon skipping events
Found 15532 exon MX events
Found 25719 alt SS events
There are 15392 alt 3 SS events and 10327 alt 5 SS events.
Found 10071 RI events
==========

ase: 3.783489227294922
count: 20.1750009059906
Processing count files.
Traceback (most recent call last):
  File "/Users/magdamaslon/rmats_turbo_v4_1_2/rmats.py", line 595, in <module>
    main()
  File "/Users/magdamaslon/rmats_turbo_v4_1_2/rmats.py", line 581, in main
    process_counts(jc_it % (event_type), args.tstat, 'JC', event_type,
  File "/Users/magdamaslon/rmats_turbo_v4_1_2/rmats.py", line 428, in process_counts
    subprocess.call([rmats_c, '-i', istat, '-t', str(tstat), '-o', ostat_pv, '-c', str(cstat),], stdout=FNULL)
  File "/usr/local/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 389, in call
    with Popen(*popenargs, **kwargs) as p:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 1024, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 1901, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/magdamaslon/rmats_turbo_v4_1_2/rMATS_C/rMATSexe'

![files](https://user-images.githubusercontent.com/23424217/221843239-93ce5d5b-a2bd-45d3-ba93-d0346b327be3.png)

**Comment by EricKutschera** [comment]
This is the main error: `FileNotFoundError: [Errno 2] No such file or directory: '/Users/magdamaslon/rmats_turbo_v4_1_2/rMATS_C/rMATSexe'`

How did you install rmats? Based on the error message it seems there was an issue during the build which caused `rMATS_C/rMATSexe` not to be compiled

You could also try installing rmats from conda:
```
conda create --prefix ./rmats_env
conda activate ./rmats_env
conda install -c conda-forge -c bioconda rmats=4.1.2
