### ISSUE TITLE
rMATS_result_FDR.txt: No such file or directory

### ISSUE THREAD

**Issue by andrepessoni** [Xinglab/rmats-turbo#272]
Hello, 
I'm using rmats 4.1.1 and it works fine until I get to the --task stat part. Before the statistics, use this command:
python rmats.py --b1 b1.txt --b2 b2.txt --gtf gencode.v39.basic.annotation.gtf -t paired --readLength 50 --nthread 6 --od output_new/ --tmp tmp_new/ --task both --statoff

Then I get this error when I run stat (python rmats.py --od output_new/ --tmp tmp_new/ --task stat):
Traceback (most recent call last):
  File "/home/.local/easybuild/software/2020/avx2/Compiler/gcc9/rmats/4.1.1/rMATS_P/FDR.py", line 45, in <module>
    ifile=open(sys.argv[1]);title=ifile.readline();
FileNotFoundError: [Errno 2] No such file or directory: 'output_new/tmp/JC_SE/rMATS_result_P-V.txt'
paste: output_new/tmp/JC_SE/rMATS_result_FDR.txt: No such file or directory

I have several errors, the same error for each event. I checked a few other similar issues, but nothing worked for me.
The file "rMATS_result_P-V.txt" is really not created, I have all the raw input files, and the only values missing in the final files are pvalue and FDR, but when I run stat they become empty files.

Thanks in advance!

**Comment by EricKutschera** [comment]
Here's the part of the code where the statistical test is run: https://github.com/Xinglab/rmats-turbo/blob/v4.1.1/rmats.py#L415

The error message is saying that FDR.py can't find output_new/tmp/JC_SE/rMATS_result_P-V.txt

That file is in the code as `ostat_pv` which should get created on the line I linked above. That line tries to run:
`./rMATS_C/rMATSexe -i output_new/JC.raw.input.SE.txt -t 1 -o output_new/tmp/JC_SE/rMATS_result_P-V.txt -c 0.0001 > /dev/null`

My guess is that there was an error running that command. The stdout for that command is sent to dev null because it prints a lot of output which is not useful when things are running correctly

You could try manually running the rMATS_C/rMATSexe command to check for an error message.
Or, you could edit your rmats.py at that line so that the output is printed by removing `, stdout=FNULL`:
`subprocess.call([rmats_c, '-i', istat, '-t', str(tstat), '-o', ostat_pv, '-c', str(cstat),])`

**Comment by EricKutschera** [comment]
The error about UTF-8 seems strange. `./rMATS_C/rMATSexe` is an executable file compiled from C source code. The error seems to be saying that Python tried to read it as a text file, but Python should not be using that file at all. What command did you run?

When you removed `stdout=FNULL` did you get any additional error message? I expected it to still fail like before, but hopefully there was an additional message saying why the rMATSexe command is failing

**Comment by andrepessoni** [comment]
In the end, I tried to install in another machine and it worked without error.
Anyway, thanks a lot for the help and fast replies.

**Comment by ehteshamuli** [comment]
Hi, I am working in an HPC environment and we are facing the same error as above of the rMATS_result_P-V.txt"  not being created. Since @andrepessoni changed machine we presume that it maybe a dependency issue?
Here is our error:
Done processing each gene from dictionary to compile AS events
Found 44645 exon skipping events
Found 6002 exon MX events
Found 30223 alt SS events
There are 15143 alt 3 SS events and 15080 alt 5 SS events.
Found 6363 RI events
==========

ase: 2.28056001663208
count: 1.7884345054626465
Processing count files.
Traceback (most recent call last):
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Compiler/gcc9/rmats/4.1.2/rMATS_P/FDR.py", line 53, in <module>
    ifile=open(sys.argv[1]);title=ifile.readline();
FileNotFoundError: [Errno 2] No such file or directory: '/home/ehtesham/projects/def-stanford-ab/ehtesham/tmp/JC_SE/rMATS_result_P-V.txt'

**Comment by ehteshamuli** [comment]
Hi,
I am working in an HPC environment and we are facing the same issue of the rMATS_result_P-V.txt not being created. Since @andrepessoni fixed the issue by changing a machine we presume it is a dependency issue?

Here is my error:

Done processing each gene from dictionary to compile AS events
Found 44645 exon skipping events
Found 6002 exon MX events
Found 30223 alt SS events
There are 15143 alt 3 SS events and 15080 alt 5 SS events.
Found 6363 RI events

ase: 2.28056001663208
count: 1.7884345054626465
Processing count files.
Traceback (most recent call last):
  File "/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Compiler/gcc9/rmats/4.1.2/rMATS_P/FDR.py", line 53, in <module>
    ifile=open(sys.argv[1]);title=ifile.readline();
FileNotFoundError: [Errno 2] No such file or directory: '/home/ehtesham/projects/def-stanford-ab/ehtesham/tmp/JC_SE/rMATS_result_P-V.txt'

**Comment by EricKutschera** [comment]
As mentioned above, the `FileNotFoundError` indicates that an earlier command failed to produce an output file. You could try running that command to see if it gives a more useful error message. The command should be something like:
```
/cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Compiler/gcc9/rmats/4.1.2/rMATS_C/rMATSexe -i /home/ehtesham/projects/def-stanford-ab/ehtesham/JC.raw.input.SE.txt -t 1 -o /home/ehtesham/projects/def-stanford-ab/ehtesham/tmp/JC_SE/rMATS_result_P-V.txt -c 0.0001
```

**Comment by ehteshamuli** [comment]
Hi Eric,
Thanks for the feedback. Sorry if this is a naive question. The command that led to the error was: 
_python $EBROOTRMATS/rmats.py --s1 ~/projects/def-stanford-ab/ehtesham/s1.txt --s2 ~/projects/def-stanford-ab/ehtesham/s2.txt --gtf ~/projects/def-stanford-ab/ehtesham/hg38.ncbiRefSeq.gtf --bi ~/projects/def-stanford-ab/ehtesham/STARindexFolder -t single --readLength 50 --od ~/projects/def-stanford-ab/ehtesham --tmp ~/projects/def-stanford-ab/ehtesham_

Should we incorporate your suggested command to it?

**Comment by ehteshamuli** [comment]
Hi Eric. Thanks for the help. I have run the command now it gives out a different error:
`bash: /home/ehtesham/.local/easybuild/software/2020/avx2/Compiler/gcc9/rmats/4.3.0/rMATS_P/rMATSexe: No such file or directory`

**Comment by EricKutschera** [comment]
`rMATSexe` is the executable file that runs the statistical test. If you built rMATS then you should have that file at some path. The path you posted ends with `rMATS_P/rMATSexe` but that file should be at a path that ends with `rMATS_C/rMATSexe`
