### ISSUE TITLE
rmatspipeline/rmatspipeline.pyx: cannot find cimported module 'nogilbam'

### ISSUE THREAD

**Issue by MSQ-123** [Xinglab/rmats-turbo#312]
I run ./build_rmats to build the rmats, but it displayed these:

Warning: Extension name 'rmats.rmatspipeline' does not match fully qualified name 'rmatspipeline' of 'rmatspipeline/rmatspipeline.pyx'
rmatspipeline/rmatspipeline.pyx: cannot find cimported module 'nogilbam'
rmatspipeline/rmatspipeline.pyx: cannot find cimported module 'rmatspipeline_declarations'
Compiling rmatspipeline/rmatspipeline.pyx because it changed.
[1/1] Cythonizing rmatspipeline/rmatspipeline.pyx

Error compiling Cython file:
------------------------------------------------------------
...
from libcpp.map cimport map as cmap
from libcpp.pair cimport pair
from libcpp.string cimport string
from libcpp.vector cimport vector
from libcpp.unordered_map cimport unordered_map
from libcpp.algorithm cimport sort, lower_bound
^
------------------------------------------------------------

rmatspipeline/rmatspipeline_declarations.pxd:8:0: 'libcpp/algorithm/lower_bound.pxd' not found

Error compiling Cython file:
------------------------------------------------------------
...
                    else:
                        tran.second = -1
                    candidates[leftanchor[j]].push_back(tran)
                    exon.first = -leftanchor[j].right
                    exon.second = deref(ctx).second.exons[i].second
                    iexon = lower_bound(gene.idx_exon.begin(), gene.idx_exon.end(), exon)
                                                          ^
could you please help me with this? thank you! @EricKutschera

**Comment by EricKutschera** [comment]
It looks like the main error is for this line: https://github.com/Xinglab/rmats-turbo/blob/master/rMATS_pipeline/rmatspipeline/rmatspipeline_declarations.pxd#L8
`rmatspipeline/rmatspipeline_declarations.pxd:8:0: 'libcpp/algorithm/lower_bound.pxd' not found`

That error seems related to the error above: `cannot find cimported module 'rmatspipeline_declarations'`

Here is the definition of lower_bound in the cython libraries: https://github.com/cython/cython/blob/master/Cython/Includes/libcpp/algorithm.pxd#L215

I'm not sure why Cython is looking for libcpp/algorithm/lower_bound.pxd when the definition is in libcpp/algorithm.pxd

What version of Cython are you using? I've tested recently with Cython v0.29.36. I was also able to use Cython v3.0.0 after the change in this comment: https://github.com/Xinglab/rmats-turbo/issues/304#issuecomment-1664189767

**Comment by MSQ-123** [comment]
@EricKutschera My Cython is 0.25.2, maybe I need to update it?
I have also tried rmats pre-built version, but it called memory error:

Traceback (most recent call last):
  File "./rMATS.4.0.1/rMATS-turbo-Linux-UCS4/rmats.py", line 308, in <module>
    main()
  File "./rMATS.4.0.1/rMATS-turbo-Linux-UCS4/rmats.py", line 283, in main
    run_pipe(args)
  File "rmatspipeline/rmatspipeline.pyx", line 2547, in rmatspipeline.run_pipe (rmatspipeline/rmatspipeline.cpp:24961)
MemoryError

**Comment by EricKutschera** [comment]
I tried building with Cython 0.25.2 and got similar errors to what you posted above. Then I upgraded to Cython 0.26.1 and was able to build successfully

The MemoryError is from rMATS v4.0.1 which is an older version. You could try installing v4.1.2 from conda: https://anaconda.org/bioconda/rmats
https://github.com/Xinglab/rmats-turbo/issues/304#issuecomment-1621728170

**Comment by MSQ-123** [comment]
> I tried building with Cython 0.25.2 and got similar errors to what you posted above. Then I upgraded to Cython 0.26.1 and was able to build successfully
> 
> The MemoryError is from rMATS v4.0.1 which is an older version. You could try installing v4.1.2 from conda: https://anaconda.org/bioconda/rmats [#304 (comment)](https://github.com/Xinglab/rmats-turbo/issues/304#issuecomment-1621728170)

@EricKutschera I still can not build v4.1.2 on mac M1, could you please release a pre-build version? the error I encountered:
clang: error: unsupported option '-fopenmp'
Thanks a lot!

**Comment by EricKutschera** [comment]
Here's a post that includes the error for unsupported option -fopenmp: https://groups.google.com/g/rmats-user-group/c/m44b0hAL6Kw/m/e2b7TOEhBAAJ

The solution was to use gcc by setting the CXX and CC environment variables

rMATS builds are available from bioconda: https://anaconda.org/bioconda/rmats
But bioconda doesn't support mac M1 yet: https://github.com/bioconda/bioconda-utils/issues/706

You could try using a docker image: https://hub.docker.com/r/xinglab/rmats
Or running a linux virtual machine on your mac
