### ISSUE TITLE
ValueError: invalid literal for int() with base 10:

### ISSUE THREAD

**Issue by mbrose2022** [Xinglab/rmats-turbo#322]
Gor rMATS installed, but got an error on the first run. Here's the command I'm running:

python rmats.py \
    --b1 /home/mbrose/data/BAMlist/c22_PBS_15wk.txt \
    --b2 /home/mbrose/data/BAMlist/wt_baseline_15wk.txt \
    --gtf /home/mbrose/STAR/mouse50/gencode.vM33.primary_assembly.annotation.gtf \
    --od /home/mbrose/data/rMATS_output/wt_c22-pbs \
    --tmp /home/mbrose/data/tmp \
    --readLength 50 \
    -t single \
    --variable-read-length \
    --nthread 4

The error I'm getting:
gtf: 9.78335452079773
There are 56941 distinct gene ID in the gtf file
There are 149547 distinct transcript ID in the gtf file
There are 35471 one-transcript genes in the gtf file
There are 869452 exons in the gtf file
There are 28169 one-exon transcripts in the gtf file
There are 22802 one-transcript genes with only one exon in the transcript
Average number of transcripts per gene is 2.626350
Average number of exons per transcript is 5.813905
Average number of exons per transcript excluding one-exon tx is 6.931100
Average number of gene per geneGroup is 7.532353
statistic: 0.015395164489746094
Fail to open /home/mbrose/data/aligned/SRR6032017_Aligned.sortedByCoord.out.bam
/home/mbrose/data/aligned/SRR6032018_Aligned.sortedByCoord.out.bam
/home/mbrose/data/aligned/SRR6032019_Aligned.sortedByCoord.out.bam
/home/mbrose/data/aligned/SRR6032020_Aligned.sortedByCoord.out.bam
/home/mbrose/data/aligned/SRR6032021_Aligned.sortedByCoord.out.bam
/home/mbrose/data/aligned/SRR6032022_Aligned.sortedByCoord.out.bam
/home/mbrose/data/aligned/SRR6032023_Aligned.sortedByCoord.out.bam
/home/mbrose/data/aligned/SRR6032024_Aligned.sortedByCoord.out.bam
Fail to open /home/mbrose/data/aligned/SRR6032001_Aligned.sortedByCoord.out.bam
/home/mbrose/data/aligned/SRR6032002_Aligned.sortedByCoord.out.bam
/home/mbrose/data/aligned/SRR6032003_Aligned.sortedByCoord.out.bam
/home/mbrose/data/aligned/SRR6032004_Aligned.sortedByCoord.out.bam
/home/mbrose/data/aligned/SRR6032005_Aligned.sortedByCoord.out.bam
/home/mbrose/data/aligned/SRR6032006_Aligned.sortedByCoord.out.bam
/home/mbrose/data/aligned/SRR6032007_Aligned.sortedByCoord.out.bam
/home/mbrose/data/aligned/SRR6032008_Aligned.sortedByCoord.out.bam

read outcome totals across all BAMs
USED: 0
NOT_PAIRED: 0
NOT_NH_1: 0
NOT_EXPECTED_CIGAR: 0
NOT_EXPECTED_READ_LENGTH: 0
NOT_EXPECTED_STRAND: 0
EXON_NOT_MATCHED_TO_ANNOTATION: 0
JUNCTION_NOT_MATCHED_TO_ANNOTATION: 0
CLIPPED: 0
total: 0
outcomes by BAM written to: /home/mbrose/data/tmp/2023-09-19-14_40_44_139071_read_outcomes_by_bam.txt

novel: 0.0016102790832519531
The splicing graph and candidate read have been saved into /home/mbrose/data/tmp/2023-09-19-14_40_44_139071_*.rmats
save: 0.00024318695068359375
WARNING: A .rmats file was found with no bams listed in it. Ignoring that file: /home/mbrose/data/tmp/2023-09-19-14_24_30_043170_0.rmats
Traceback (most recent call last):
  File "/home/mbrose/rMATS/rmats.py", line 595, in <module>
    main()
  File "/home/mbrose/rMATS/rmats.py", line 563, in main
    run_pipe(args)
  File "rmatspipeline/rmatspipeline.pyx", line 3860, in rmats.rmatspipeline.run_pipe
  File "rmatspipeline/rmatspipeline.pyx", line 3723, in rmats.rmatspipeline.split_sg_files_by_bam
  File "rmatspipeline/rmatspipeline.pyx", line 3731, in rmats.rmatspipeline.split_sg_files_by_bam
ValueError: invalid literal for int() with base 10: '/home/mbrose/data/aligned/SRR6032018_Aligned.sortedByCoord.out.bam'

I've checked the two files it says it failed on with samtools and they're fine. They are both at the beginning of their respective text files though. 

The files are formatted like this:
/home/mbrose/data/aligned/SRR6032001_Aligned.sortedByCoord.out.bam
/home/mbrose/data/aligned/SRR6032002_Aligned.sortedByCoord.out.bam
/home/mbrose/data/aligned/SRR6032003_Aligned.sortedByCoord.out.bam
/home/mbrose/data/aligned/SRR6032004_Aligned.sortedByCoord.out.bam
/home/mbrose/data/aligned/SRR6032005_Aligned.sortedByCoord.out.bam
/home/mbrose/data/aligned/SRR6032006_Aligned.sortedByCoord.out.bam
/home/mbrose/data/aligned/SRR6032007_Aligned.sortedByCoord.out.bam
/home/mbrose/data/aligned/SRR6032008_Aligned.sortedByCoord.out.bam

**Comment by EricKutschera** [comment]
That looks like the same error as in this post: https://github.com/Xinglab/rmats-turbo/issues/191

The --b1 and --b2 files need to have the bams separated by commas like:
```
/home/mbrose/data/aligned/SRR6032018_Aligned.sortedByCoord.out.bam,/home/mbrose/data/aligned/SRR6032019_Aligned.sortedByCoord.out.bam,/home/mbrose/data/aligned/SRR6032020_Aligned.sortedByCoord.out.bam,/home/mbrose/data/aligned/SRR6032021_Aligned.sortedByCoord.out.bam,/home/mbrose/data/aligned/SRR6032022_Aligned.sortedByCoord.out.bam,/home/mbrose/data/aligned/SRR6032023_Aligned.sortedByCoord.out.bam,/home/mbrose/data/aligned/SRR6032024_Aligned.sortedByCoord.out.bam
```

**Comment by mbrose2022** [comment]
Ok, I changed all the paths to comma separated, and rMATS runs for about 15 minutes,
 but then I still get the error
$ ./c22-ASO-vs-PBS.sh
gtf: 10.748642683029175
There are 56941 distinct gene ID in the gtf file
There are 149547 distinct transcript ID in the gtf file
There are 35471 one-transcript genes in the gtf file
There are 869452 exons in the gtf file
There are 28169 one-exon transcripts in the gtf file
There are 22802 one-transcript genes with only one exon in the transcript
Average number of transcripts per gene is 2.626350
Average number of exons per transcript is 5.813905
Average number of exons per transcript excluding one-exon tx is 6.931100
Average number of gene per geneGroup is 7.532353
statistic: 0.016892194747924805
^@
read outcome totals across all BAMs
USED: 8753061
NOT_PAIRED: 0
NOT_NH_1: 0
NOT_EXPECTED_CIGAR: 37592
NOT_EXPECTED_READ_LENGTH: 0
NOT_EXPECTED_STRAND: 0
EXON_NOT_MATCHED_TO_ANNOTATION: 692966
JUNCTION_NOT_MATCHED_TO_ANNOTATION: 64609
CLIPPED: 69750045
total: 79298273
outcomes by BAM written to: /home/mbrose/data/tmp/2023-09-19-18_26_38_908525_read_outcomes_by_bam.txt

novel: 942.7413635253906
The splicing graph and candidate read have been saved into /home/mbrose/data/tmp/2023-09-19-18_26_38_908525_*.rmats
save: 0.5043683052062988
WARNING: A .rmats file was found with no bams listed in it. Ignoring that file: /home/mbrose/data/tmp/2023-09-19-14_24_30_043170_0.rmats
Traceback (most recent call last):
  File "/home/mbrose/rMATS/rmats.py", line 595, in <module>
    main()
  File "/home/mbrose/rMATS/rmats.py", line 563, in main
    run_pipe(args)
  File "rmatspipeline/rmatspipeline.pyx", line 3860, in rmats.rmatspipeline.run_pipe
  File "rmatspipeline/rmatspipeline.pyx", line 3723, in rmats.rmatspipeline.split_sg_files_by_bam
  File "rmatspipeline/rmatspipeline.pyx", line 3731, in rmats.rmatspipeline.split_sg_files_by_bam
ValueError: invalid literal for int() with base 10: '/home/mbrose/data/aligned/SRR6032018_Aligned.sortedByCoord.out.bam'


Should the files with the paths have a newline after the big string with all the paths?

I also tried running it with the string of paths directly in the command, but that gave me an error about expecting a path to a file.

**Comment by mbrose2022** [comment]
Making progress; realized I was searching the repo instead of the forum here, found another user with similar problems who solved them by emptying out the tmp directory. Still getting various PATH errors but eliminating them one by one, hopefully.
