### ISSUE TITLE
Errors while use rmats-4.1.2

### ISSUE THREAD

**Issue by circR** [Xinglab/rmats-turbo#337]
Hi,
I tried to use the rmats-4.1.2 version since I could not build the turbo version.
The installation seemed OK, but when I run the script below, it showed some errors.
Could you help with this? Thank you a lot.
Script：
"rmats.py --b1 b1.txt --b2 b2.txt --gtf /home/cd/RNAseq/c_elegans_WBcel235.gtf --readLength 150 --nthread 24 --od . --tmp ../tmp"
Output:
gtf: 1.4780969619750977
There are 20222 distinct gene ID in the gtf file
There are 34035 distinct transcript ID in the gtf file
There are 13923 one-transcript genes in the gtf file
There are 237194 exons in the gtf file
There are 773 one-exon transcripts in the gtf file
There are 509 one-transcript genes with only one exon in the transcript
Average number of transcripts per gene is 1.683068
Average number of exons per transcript is 6.969120
Average number of exons per transcript excluding one-exon tx is 7.107841
Average number of gene per geneGroup is 4.194180
statistic: 0.0032558441162109375

read outcome totals across all BAMs
USED: 0
NOT_PAIRED: 0
NOT_NH_1: 69692990
NOT_EXPECTED_CIGAR: 4427510
NOT_EXPECTED_READ_LENGTH: 444779174
NOT_EXPECTED_STRAND: 0
EXON_NOT_MATCHED_TO_ANNOTATION: 0
JUNCTION_NOT_MATCHED_TO_ANNOTATION: 0
CLIPPED: 215872124
total: 734771798
outcomes by BAM written to: ../tmp/2023-10-26-16_01_43_750197_read_outcomes_by_bam.txt

novel: 462.9496338367462
The splicing graph and candidate read have been saved into ../tmp/2023-10-26-16_01_43_750197_*.rmats
save: 0.0011670589447021484
Traceback (most recent call last):
  File "/home/cd/miniconda3/envs/new_rmats_conda_env/bin/rmats.py", line 595, in <module>
    main()
  File "/home/cd/miniconda3/envs/new_rmats_conda_env/bin/rmats.py", line 563, in main
    run_pipe(args)
  File "rmatspipeline/rmatspipeline.pyx", line 3860, in rmats.rmatspipeline.run_pipe
  File "rmatspipeline/rmatspipeline.pyx", line 3723, in rmats.rmatspipeline.split_sg_files_by_bam
  File "rmatspipeline/rmatspipeline.pyx", line 3731, in rmats.rmatspipeline.split_sg_files_by_bam
ValueError: invalid literal for int() with base 10: '/home/cd/RNAseq/S2_Aligned.sortedByCoord.out.bam'

**Comment by EricKutschera** [comment]
Here's the line of code from that stack trace: https://github.com/Xinglab/rmats-turbo/blob/v4.1.2/rMATS_pipeline/rmatspipeline/rmatspipeline.pyx#L3731

That code looks for all the `.rmats` files under the `--tmp` directory. For each `.rmats` file it finds it expects to find the bam file on the 1st line and then the read length on the 2nd line. The error is saying that it found a bam name (`/home/cd/RNAseq/S2_Aligned.sortedByCoord.out.bam`) instead of a read length on the second line of a `.rmats` file that it found

It could be that your `--b1` or `--b2` file is not formatted as expected (https://github.com/Xinglab/rmats-turbo/issues/191)
