### ISSUE TITLE
no result with rmats-turbo 4.1.2

### ISSUE THREAD

**Issue by mick42-star** [Xinglab/rmats-turbo#338]
Hi,
I am using rmats-turbo 4.1.2. I also checked ulimit -Ss (which is unlimited). But my results files are all empty only with header.

Done processing each gene from dictionary to compile AS events
Found 29525 exon skipping events
Found 1709 exon MX events
Found 9929 alt SS events
There are 6252 alt 3 SS events and 3677 alt 5 SS events.
Found 4579 RI events

/data/apps/extern/rmats-turbo/4.1.2/rMATS_C/rMATSexe: error while loading shared libraries: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/data/apps/extern/rmats-turbo/4.1.2/rMATS_P/FDR.py", line 53, in <module>
    ifile=open(sys.argv[1]);title=ifile.readline();
FileNotFoundError: [Errno 2] No such file or directory: '/data/adoetzl2/Jag1_organoid/rmats/tmp/JC_SE/rMATS_result_P-V.txt'
paste: /data/adoetzl2/Jag1_organoid/rmats/tmp/JC_SE/rMATS_result_FDR.txt: No such file or directory
/data/apps/extern/rmats-turbo/4.1.2/rMATS_C/rMATSexe: error while loading shared libraries: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/data/apps/extern/rmats-turbo/4.1.2/rMATS_P/FDR.py", line 53, in <module>
    ifile=open(sys.argv[1]);title=ifile.readline();
FileNotFoundError: [Errno 2] No such file or directory: '/data/adoetzl2/Jag1_organoid/rmats/tmp/JCEC_SE/rMATS_result_P-V.txt'
paste: /data/adoetzl2/Jag1_organoid/rmats/tmp/JCEC_SE/rMATS_result_FDR.txt: No such file or directory
/data/apps/extern/rmats-turbo/4.1.2/rMATS_C/rMATSexe: error while loading shared libraries: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/data/apps/extern/rmats-turbo/4.1.2/rMATS_P/FDR.py", line 53, in <module>
    ifile=open(sys.argv[1]);title=ifile.readline();
FileNotFoundError: [Errno 2] No such file or directory: '/data/adoetzl2/Jag1_organoid/rmats/tmp/JC_MXE/rMATS_result_P-V.txt'
paste: /data/adoetzl2/Jag1_organoid/rmats/tmp/JC_MXE/rMATS_result_FDR.txt: No such file or directory
/data/apps/extern/rmats-turbo/4.1.2/rMATS_C/rMATSexe: error while loading shared libraries: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/data/apps/extern/rmats-turbo/4.1.2/rMATS_P/FDR.py", line 53, in <module>
    ifile=open(sys.argv[1]);title=ifile.readline();
FileNotFoundError: [Errno 2] No such file or directory: '/data/adoetzl2/Jag1_organoid/rmats/tmp/JCEC_MXE/rMATS_result_P-V.txt'
paste: /data/adoetzl2/Jag1_organoid/rmats/tmp/JCEC_MXE/rMATS_result_FDR.txt: No such file or directory
/data/apps/extern/rmats-turbo/4.1.2/rMATS_C/rMATSexe: error while loading shared libraries: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/data/apps/extern/rmats-turbo/4.1.2/rMATS_P/FDR.py", line 53, in <module>
    ifile=open(sys.argv[1]);title=ifile.readline();
FileNotFoundError: [Errno 2] No such file or directory: '/data/adoetzl2/Jag1_organoid/rmats/tmp/JC_A3SS/rMATS_result_P-V.txt'
paste: /data/adoetzl2/Jag1_organoid/rmats/tmp/JC_A3SS/rMATS_result_FDR.txt: No such file or directory
/data/apps/extern/rmats-turbo/4.1.2/rMATS_C/rMATSexe: error while loading shared libraries: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/data/apps/extern/rmats-turbo/4.1.2/rMATS_P/FDR.py", line 53, in <module>
    ifile=open(sys.argv[1]);title=ifile.readline();
FileNotFoundError: [Errno 2] No such file or directory: '/data/adoetzl2/Jag1_organoid/rmats/tmp/JCEC_A3SS/rMATS_result_P-V.txt'
paste: /data/adoetzl2/Jag1_organoid/rmats/tmp/JCEC_A3SS/rMATS_result_FDR.txt: No such file or directory
/data/apps/extern/rmats-turbo/4.1.2/rMATS_C/rMATSexe: error while loading shared libraries: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/data/apps/extern/rmats-turbo/4.1.2/rMATS_P/FDR.py", line 53, in <module>
    ifile=open(sys.argv[1]);title=ifile.readline();
FileNotFoundError: [Errno 2] No such file or directory: '/data/adoetzl2/Jag1_organoid/rmats/tmp/JC_A5SS/rMATS_result_P-V.txt'
paste: /data/adoetzl2/Jag1_organoid/rmats/tmp/JC_A5SS/rMATS_result_FDR.txt: No such file or directory
/data/apps/extern/rmats-turbo/4.1.2/rMATS_C/rMATSexe: error while loading shared libraries: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/data/apps/extern/rmats-turbo/4.1.2/rMATS_P/FDR.py", line 53, in <module>
    ifile=open(sys.argv[1]);title=ifile.readline();
FileNotFoundError: [Errno 2] No such file or directory: '/data/adoetzl2/Jag1_organoid/rmats/tmp/JCEC_A5SS/rMATS_result_P-V.txt'
paste: /data/adoetzl2/Jag1_organoid/rmats/tmp/JCEC_A5SS/rMATS_result_FDR.txt: No such file or directory
/data/apps/extern/rmats-turbo/4.1.2/rMATS_C/rMATSexe: error while loading shared libraries: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/data/apps/extern/rmats-turbo/4.1.2/rMATS_P/FDR.py", line 53, in <module>
    ifile=open(sys.argv[1]);title=ifile.readline();
FileNotFoundError: [Errno 2] No such file or directory: '/data/adoetzl2/Jag1_organoid/rmats/tmp/JC_RI/rMATS_result_P-V.txt'
paste: /data/adoetzl2/Jag1_organoid/rmats/tmp/JC_RI/rMATS_result_FDR.txt: No such file or directory
/data/apps/extern/rmats-turbo/4.1.2/rMATS_C/rMATSexe: error while loading shared libraries: libgsl.so.25: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/data/apps/extern/rmats-turbo/4.1.2/rMATS_P/FDR.py", line 53, in <module>
    ifile=open(sys.argv[1]);title=ifile.readline();
FileNotFoundError: [Errno 2] No such file or directory: '/data/adoetzl2/Jag1_organoid/rmats/tmp/JCEC_RI/rMATS_result_P-V.txt'
paste: /data/adoetzl2/Jag1_organoid/rmats/tmp/JCEC_RI/rMATS_result_FDR.txt: No such file or directory

**Comment by EricKutschera** [comment]
This is the error: `/data/apps/extern/rmats-turbo/4.1.2/rMATS_C/rMATSexe: error while loading shared libraries: libgsl.so.25: cannot open shared object file: No such file or directory`

You could try https://github.com/Xinglab/rmats-turbo/issues/300 or https://github.com/Xinglab/rmats-turbo/issues/281

**Comment by mick42-star** [comment]
> This is the error: `/data/apps/extern/rmats-turbo/4.1.2/rMATS_C/rMATSexe: error while loading shared libraries: libgsl.so.25: cannot open shared object file: No such file or directory`
> 
> You could try #300 or #281

Hi Eric, thanks, the problem has been solved. It worked well when I use my fastq file as input. However, when I use processed bam file as my input, I saw the error massage.

Traceback (most recent call last):
  File "/home/hhuan121/new_conda_env/bin/rmats.py", line 595, in <module>
    main()
  File "/home/hhuan121/new_conda_env/bin/rmats.py", line 558, in main
    args = get_args()
  File "/home/hhuan121/new_conda_env/bin/rmats.py", line 203, in get_args
    args.b1, args.b2 = doSTARMapping(args)
  File "/home/hhuan121/new_conda_env/bin/rmats.py", line 76, in doSTARMapping
    status,output = getstatusoutput(cmd)
  File "/home/hhuan121/new_conda_env/bin/rmats.py", line 40, in getstatusoutput
    output = output.decode()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1039: invalid start byte

I tried to add LC_ALL=en_US.UTF-8 , but it doesn't work.

**Comment by LI-zijian1** [comment]
Hi，You can check whether your path or file name contains Chinese characters.

**Comment by mick42-star** [comment]
> Hi，You can check whether your path or file name contains Chinese characters.

Hi, it doesn't have any Chinese characters.

**Comment by LI-zijian1** [comment]
> > Hi，You can check whether your path or file name contains Chinese characters.
> 
> Hi, it doesn't have any Chinese characters.

I encountered the problem of UnicodeDecodeError: 'utf-8' yesterday. The reason is that the input path and file name contain Chinese characters. It seems that this does not apply to your problem. There may be problems with other characters. Hope you can resolve this problem and good luck.

**Comment by EricKutschera** [comment]
From the traceback it looks like the error came from `doSTARMapping`. If you used bam files as input then rMATS should not try to run STAR. Did you run with `--s1` and `--s2`? BAM files should be given with `--b1` and `--b2`

**Comment by mick42-star** [comment]
> C_ALL=en_US.UTF-8 , but it doesn't wor

Thanks Eric. I forgot to change to --b1 and b2. It now working well.
