### ISSUE TITLE
STAR: command not found when running rmats.py

### ISSUE THREAD

**Issue by HadesK9** [Xinglab/rmats-turbo#342]
I'm trying to run rmats, the build and test ran perfectly but whenever I try to actually run rmats.py i get this issue. I'm using this code:

$ python3 rmats.py --s1 files/s1.txt --s2 files/s2.txt --gtf path/to/the.gtf --bi path/to/STAR_binary_index -t paired --readLength 50 --nthread 4 --od output --tmp tmp_output

and this is the error message:

mapping the first sample
mapping sample_0, /rmats-turbo-4.2.0/files/1.gz is done with status 127
error in mapping sample_0, /rmats-turbo-4.2.0/files/1.gz: 127
error detail: /bin/sh: STAR: command not found
Traceback (most recent call last):
  File "rmats.py", line 596, in <module>
    main()
  File "rmats.py", line 559, in main
    args = get_args()
  File "rmats.py", line 204, in get_args
    args.b1, args.b2 = doSTARMapping(args)
  File "rmats.py", line 82, in doSTARMapping
    raise Exception()
Exception

**Comment by EricKutschera** [comment]
Since you are running with `--s1` rMATS will try to run STAR, but it looks like STAR is not installed: `STAR: command not found`

The STAR github has instructions for building it from source: https://github.com/alexdobin/STAR

Another option is to install STAR with conda: https://docs.conda.io/projects/miniconda/en/latest/

If you have conda installed you can install STAR to a new environment with:
```
conda create --prefix ./new_conda_env
conda activate ./new_conda_env
conda install -c conda-forge -c bioconda star
```
