### ISSUE TITLE
sort.bam found 3 times in .rmats files

### ISSUE THREAD

**Issue by Anees-caas** [Xinglab/rmats-turbo#347]
Hi @EricKutschera 
I am running the rmats, I have two samples each sample have 3 bam files as protocol I have run the prep step first. bam.a.text (1a.sort.bam, 2a.sort.bam, 3a.sort.bam)
python rmats.py --b1 path/to/bam.a.txt --gtf path/to/gene.gtf -t paired --readLength 150 --nthread 8 --od  path/to/out --tmp path/to/tmp_output_prep_1 --task prep
bam.b.text (1b.sort.bam, 2b.sort.bam, 3b.sort.bam) 
python rmats.py --b1 path/to/bam.b.txt --gtf path/to/gene.gtf -t paired --readLength 150 --nthread 8 --od  path/to/out --tmp path/to/tmp_output_prep_2 --task prep
The prep steps creating two directories tmp_output_prep_1 and tmp_output_prep_2,  each containing three rmats files. 
cd: tmp_output_prep_1
2023-12-06-15_25_07_884775_read_outcomes_by_bam.txt
2023-12-06-15_25_07_884775_2.rmats
2023-12-06-15_25_07_884775_1.rmats
2023-12-06-15_25_07_884775_0.rmats
cd: tmp_output_prep_2
2023-12-06-15_31_02_933677_read_outcomes_by_bam.txt
2023-12-06-15_31_02_933677_2.rmats
2023-12-06-15_31_02_933677_1.rmats
2023-12-06-15_31_02_933677_0.rmats
After this step I have put all rmats and bam in 1 directory and run the 
rmats.py --b1 /path/to/bam.a.txt --b2 path/to/bam.b.txt --gtf path/to/gene.gtf  -t paired --readLength 150 --nthread 8 --od path/to/output --tmp 
I am getting the error 
path/to/a1_sort.bam found 3 times in .rmats files
path/to/a2_sort.bam found 3 times in .rmats files
path/to/a3_sort.bam found 3 times in .rmats files
path/to/b1_sort.bam found 3 times in .rmats files
path/to/b2_sort.bam found 3 times in .rmats files
path/to/b3_sort.bam found 3 times in .rmats files

**Comment by EricKutschera** [comment]
Here's the line for that error: https://github.com/Xinglab/rmats-turbo/blob/v4.2.0/rMATS_pipeline/rmatspipeline/rmatspipeline.pyx#L3684

The code loads all the .rmats files from the --tmp directory. On the first line of each .rmats file it says which bam files it contains data for. The code expects to find each bam given in --b1 and --b2 exactly once in one of the .rmats files.

The two `--task prep` commands that you ran seem fine. You can check the first line of the .rmats files in `tmp_output_prep_1` and `tmp_output_prep_2` to make sure they have the bam names you expect

After running the prep steps you can run rmats.py with `--task post`, but it looks like you ran without specifying --task so it will default to `--task both` and run both the prep and post steps. https://github.com/Xinglab/rmats-turbo/tree/v4.2.0#running-prep-and-post-separately

**Comment by Anees-caas** [comment]
Hi when I am running the --task post i am facing these errors 
python rmats.py --b1 path/to/bam.a.txt --b2 path/to/bam.b.txt --gtf path/to/gene.gtf -t paired --readLength 100 --nthread 8 --od path/to/out --tmp path/to/tmp_output_post --task post
Traceback (most recent call last):
  File "/home/u4987/miniconda3/envs/rmats/rMATS/rmats.py", line 596, in <module>
    main()
  File "/home/u4987/miniconda3/envs/rmats/rMATS/rmats.py", line 559, in main
    args = get_args()
  File "/home/u4987/miniconda3/envs/rmats/rMATS/rmats.py", line 188, in get_args
    with open(args.b1, 'r') as fp:
FileNotFoundError: [Errno 2] No such file or directory: 'path/to/bam.a.txt'
(rmats) u4987@gsxx:~/miniconda3/envs/rmats/rMATS$

**Comment by Anees-caas** [comment]
I have skipped the --task post and run the 
python rmats.py --b1 /path/to/b1.txt --b2 /path/to/b2.txt --gtf /path/to/the.gtf -t paired --readLength 50/100/150 --nthread 4 --od /path/to/output --tmp /path/to/tmp_output
it is generating the empty files except the files from GTF as in issue #328 
For further clarification I have run the commands from the prep step again. the command run as 
gtf: 1.6981773376464844
There are 22374 distinct gene ID in the gtf file
There are 42410 distinct transcript ID in the gtf file
There are 14320 one-transcript genes in the gtf file
There are 303703 exons in the gtf file
There are 3674 one-exon transcripts in the gtf file
There are 3568 one-transcript genes with only one exon in the transcript
Average number of transcripts per gene is 1.895504
Average number of exons per transcript is 7.161118
Average number of exons per transcript excluding one-exon tx is 7.745482
Average number of gene per geneGroup is 2.524812
statistic: 0.006269931793212891

read outcome totals across all BAMs
USED: 0
NOT_PAIRED: 10619770
NOT_NH_1: 13901112
NOT_EXPECTED_CIGAR: 998350
NOT_EXPECTED_READ_LENGTH: 121560452
NOT_EXPECTED_STRAND: 0
EXON_NOT_MATCHED_TO_ANNOTATION: 0
JUNCTION_NOT_MATCHED_TO_ANNOTATION: 0
CLIPPED: 9246633
total: 156326317
outcomes by BAM written to: path/to/tmp_output_prep_1/2023-12-07-11_21_10_313593_read_outcomes_by_bam.txt

novel: 264.98194551467896
The splicing graph and candidate read have been saved into 
path/to/tmp_output_prep_1/2023-12-07-11_21_10_313593_*.rmats
save: 0.00044918060302734375
as issue #109 
Our bam files are generated using HISAT2 
as I read in issue #109 " rMATS was designed to work with short-read sequencing data and expects uniquely mapped reads. It looks like you have long-read sequencing data which rMATS is not designed to analyze" 
and the good news is you have released the espresso [https://github.com/Xinglab/espresso]. 
My question is do I have to use the espresso to execute the splicing analysis?

**Comment by Anees-caas** [comment]
Thanks for considering my questions! 
With -- --readLength when I run the --variable-read-length it worked.
