### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0x8b in position 1: ordinal not in range(128)

### ISSUE THREAD

**Issue by kerendanan1511** [Xinglab/rmats-turbo#397]
Hello, 

when running rmats.py with these parameters 

file=/a/home/cc/lifesci/kerendanan1/provide/high_quality/C017_SCR1Aligned.sortedByCoord.out.bam

output_dir=/a/home/cc/lifesci/kerendanan1/rmats_turbo/provide_rmats/C017_SCR1/rmats

GTF=/a/home/cc/lifesci/kerendanan1/rmats_turbo/gencode.v31lift37.annotation.gtf

python ~/.conda/envs/rmats_env/bin/rmats.py --b1 $file --gtf $GTF -t paired --readLength 150 --nthread 16 --od output_dir --tmp $output_dir/tmp_output --variable-read-length --novelSS --task both

I get this error: 

Traceback (most recent call last):
  File "/a/home/cc/lifesci/kerendanan1/.conda/envs/rmats_env/bin/rmats.py", line 595, in <module>
    main()
  File "/a/home/cc/lifesci/kerendanan1/.conda/envs/rmats_env/bin/rmats.py", line 558, in main
    args = get_args()
  File "/a/home/cc/lifesci/kerendanan1/.conda/envs/rmats_env/bin/rmats.py", line 188, in get_args
    args.b1 = fp.read().strip().strip(',')
  File "/a/home/cc/lifesci/kerendanan1/.conda/envs/rmats_env/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0x8b in position 1: ordinal not in range(128)

Any idea what has gone wrong? 

Thanks

**Comment by EricKutschera** [comment]
Here's the line for that error: https://github.com/Xinglab/rmats-turbo/blob/v4.1.2/rmats.py#L188

The code expects `--b1` to be a file with a single line of comma separated bam file paths: https://github.com/Xinglab/rmats-turbo/tree/v4.3.0?tab=readme-ov-file#starting-with-bam-files

Your command used a bam file directly as `--b1` (`C017_SCR1Aligned.sortedByCoord.out.bam`)

Here's a similar issue: https://github.com/Xinglab/rmats-turbo/issues/213#issuecomment-1180691170
