### ISSUE TITLE
issue with conda installation

### ISSUE THREAD

**Issue by neelroop** [Xinglab/rmats-turbo#42]
Hi,

I have previously used MATS, it was really essential to some of my previous work. I am looking forward to trying rMATS.

I have tried to install rMATS with conda as instructed. I had initially encountered a few idiosyncratic stumbling blocks with MacOSX, but found workarounds. However, I ultimately encountered the following issue when I try to run ./test_mats:

> Collecting package metadata (current_repodata.json): done
> Solving environment: done
> All requested packages already installed.
> test (tests.alternative_3_splice_site_novel.test.NovelJunction) ... FAIL
> test (tests.alternative_3_splice_site_novel.test.NovelSpliceSite) ... FAIL
> test (tests.alternative_5_splice_site_novel.test.NovelJunction) ... FAIL
> test (tests.alternative_5_splice_site_novel.test.NovelSpliceSite) ... FAIL
> test (tests.mutually_exclusive_exons_novel.test.NovelJunction) ... FAIL
> test (tests.mutually_exclusive_exons_novel.test.NovelSpliceSite) ... FAIL
> test (tests.only_one_sample.test.StatOffTest) ... FAIL
> test (tests.only_one_sample.test.StatOnTest) ... FAIL
> test (tests.paired_stats.test.FilteredEventTest) ... FAIL
> test (tests.paired_stats.test.OneEventTest) ... FAIL
> test (tests.paired_stats.test.TwoEventTest) ... FAIL
> test (tests.prep_post.test.Test) ... FAIL
> test (tests.retained_intron_novel.test.NovelJunction) ... FAIL
> test (tests.retained_intron_novel.test.NovelSpliceSite) ... FAIL
> test (tests.skipped_exon_basic.test.Test) ... FAIL
> test (tests.skipped_exon_novel.test.NovelJunction) ... FAIL
> test (tests.skipped_exon_novel.test.NovelSpliceSite) ... FAIL
> test (tests.variable_read_length.test.Length1Test) ... FAIL
> test (tests.variable_read_length.test.Length1VariableTest) ... FAIL
> test (tests.variable_read_length.test.Length2Test) ... FAIL
> test (tests.variable_read_length.test.Length2VariableTest) ... FAIL

All of the fails are similar, for example:
> FAIL: test (tests.alternative_3_splice_site_novel.test.NovelJunction)
> Traceback (most recent call last):
>   File "/Users/nnp/projects/lab/global_software/MATS/rmats-turbo/tests/alternative_3_splice_site_novel/test.py", line 95, in test
>     self._run_test()
>   File "/Users/nnp/projects/lab/global_software/MATS/rmats-turbo/tests/base_test.py", line 17, in _run_test
>     self._check_results()
>   File "/Users/nnp/projects/lab/global_software/MATS/rmats-turbo/tests/alternative_3_splice_site_novel/test.py", line 114, in _check_results
>     self._check_no_error_results()
>   File "/Users/nnp/projects/lab/global_software/MATS/rmats-turbo/tests/base_test.py", line 61, in _check_no_error_results
>     self.assertEqual(self._rmats_return_code, 0)
> AssertionError: 1 != 0

Looking in the tests directory, they all say the following in the stderror:
> Traceback (most recent call last):
>   File "/Users/nnp/projects/lab/global_software/MATS/rmats-turbo/rmats.py", line 16, in <module>
>     from rmatspipeline import run_pipe
> ImportError: dlopen(/Users/nnp/projects/lab/global_software/MATS/rmats-turbo/rmatspipeline.cpython-36m-darwin.so, 2): Symbol not found: _GOMP_parallel
>   Referenced from: /Users/nnp/projects/lab/global_software/MATS/rmats-turbo/rmatspipeline.cpython-36m-darwin.so
>   Expected in: flat namespace
>  in /Users/nnp/projects/lab/global_software/MATS/rmats-turbo/rmatspipeline.cpython-36m-darwin.so

Test run environment info:

> active environment : /Users/nnp/projects/lab/global_software/MATS/rmats-turbo/conda_envs/test_rmats
>     active env location : /Users/nnp/projects/lab/global_software/MATS/rmats-turbo/conda_envs/test_rmats
>             shell level : 2
>        user config file : /Users/nnp/.condarc
>  populated config files : 
>           conda version : 4.8.4
>     conda-build version : not installed
>          python version : 3.8.3.final.0
>        virtual packages : __osx=10.15.6
>        base environment : /Users/nnp/opt/miniconda3  (writable)
>            channel URLs : https://repo.anaconda.com/pkgs/main/osx-64
>                           https://repo.anaconda.com/pkgs/main/noarch
>                           https://repo.anaconda.com/pkgs/r/osx-64
>                           https://repo.anaconda.com/pkgs/r/noarch
>           package cache : /Users/nnp/opt/miniconda3/pkgs
>                           /Users/nnp/.conda/pkgs
>        envs directories : /Users/nnp/opt/miniconda3/envs
>                           /Users/nnp/.conda/envs
>                platform : osx-64
>              user-agent : conda/4.8.4 requests/2.24.0 CPython/3.8.3 Darwin/19.6.0 OSX/10.15.6
>                 UID:GID : 501:20
>              netrc file : None
>            offline mode : False

If it helps, even when I run ./run_rmats -h
> Traceback (most recent call last):
>   File "/Users/nnp/projects/lab/global_software/MATS/rmats-turbo/rmats.py", line 16, in <module>
>     from rmatspipeline import run_pipe
> ImportError: dlopen(/Users/nnp/projects/lab/global_software/MATS/rmats-turbo/rmatspipeline.cpython-36m-darwin.so, 2): Symbol not found: _GOMP_parallel
>   Referenced from: /Users/nnp/projects/lab/global_software/MATS/rmats-turbo/rmatspipeline.cpython-36m-darwin.so
>   Expected in: flat namespace
>  in /Users/nnp/projects/lab/global_software/MATS/rmats-turbo/rmatspipeline.cpython-36m-darwin.so

From my searches, it seems like sometimes this is related to an OpenMP issue in MacOSX. I encountered an issue related to that earlier on, and I did have to use gcc-10 to make the files in rMATS_C. Any ideas what has gone awry?

**Comment by neelroop** [comment]
I used the bioconda installation and I got around the above issue.
