### ISSUE TITLE
Multiple problems

### ISSUE THREAD

**Issue by ShenTTT** [Xinglab/rmats-turbo#81]
I got this error after running rmats:
```
==========
Done processing each gene from dictionary to compile AS events
Found 22096 exon skipping events
Found 8794 exon MX events
Found 45794 alt SS events
There are 23930 alt 3 SS events and 21864 alt 5 SS events.
Found 3045 RI events
==========

ase: 4.3597495555877686
count: 174.3783712387085
Processing count files.
/home/nus/Desktop/NGS/rmats-turbo/rMATS_C/rMATSexe: error while loading shared libraries: libgsl.so.23: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/home/nus/Desktop/NGS/rmats-turbo/rMATS_P/FDR.py", line 45, in <module>
    ifile=open(sys.argv[1]);title=ifile.readline();
FileNotFoundError: [Errno 2] No such file or directory: '/media/nus/AMLab_Ext1/Shen/splicing/try/temp_output/JC_SE/rMATS_result_P-V.txt'
paste: /media/nus/AMLab_Ext1/Shen/splicing/try/temp_output/JC_SE/rMATS_result_FDR.txt: No such file or directory
/home/nus/Desktop/NGS/rmats-turbo/rMATS_C/rMATSexe: error while loading shared libraries: libgsl.so.23: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/home/nus/Desktop/NGS/rmats-turbo/rMATS_P/FDR.py", line 45, in <module>
    ifile=open(sys.argv[1]);title=ifile.readline();
FileNotFoundError: [Errno 2] No such file or directory: '/media/nus/AMLab_Ext1/Shen/splicing/try/temp_output/JCEC_SE/rMATS_result_P-V.txt'
paste: /media/nus/AMLab_Ext1/Shen/splicing/try/temp_output/JCEC_SE/rMATS_result_FDR.txt: No such file or directory
/home/nus/Desktop/NGS/rmats-turbo/rMATS_C/rMATSexe: error while loading shared libraries: libgsl.so.23: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/home/nus/Desktop/NGS/rmats-turbo/rMATS_P/FDR.py", line 45, in <module>
    ifile=open(sys.argv[1]);title=ifile.readline();
FileNotFoundError: [Errno 2] No such file or directory: '/media/nus/AMLab_Ext1/Shen/splicing/try/temp_output/JC_MXE/rMATS_result_P-V.txt'
paste: /media/nus/AMLab_Ext1/Shen/splicing/try/temp_output/JC_MXE/rMATS_result_FDR.txt: No such file or directory
/home/nus/Desktop/NGS/rmats-turbo/rMATS_C/rMATSexe: error while loading shared libraries: libgsl.so.23: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/home/nus/Desktop/NGS/rmats-turbo/rMATS_P/FDR.py", line 45, in <module>
    ifile=open(sys.argv[1]);title=ifile.readline();
FileNotFoundError: [Errno 2] No such file or directory: '/media/nus/AMLab_Ext1/Shen/splicing/try/temp_output/JCEC_MXE/rMATS_result_P-V.txt'
paste: /media/nus/AMLab_Ext1/Shen/splicing/try/temp_output/JCEC_MXE/rMATS_result_FDR.txt: No such file or directory
/home/nus/Desktop/NGS/rmats-turbo/rMATS_C/rMATSexe: error while loading shared libraries: libgsl.so.23: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/home/nus/Desktop/NGS/rmats-turbo/rMATS_P/FDR.py", line 45, in <module>
    ifile=open(sys.argv[1]);title=ifile.readline();
FileNotFoundError: [Errno 2] No such file or directory: '/media/nus/AMLab_Ext1/Shen/splicing/try/temp_output/JC_A3SS/rMATS_result_P-V.txt'
paste: /media/nus/AMLab_Ext1/Shen/splicing/try/temp_output/JC_A3SS/rMATS_result_FDR.txt: No such file or directory
/home/nus/Desktop/NGS/rmats-turbo/rMATS_C/rMATSexe: error while loading shared libraries: libgsl.so.23: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/home/nus/Desktop/NGS/rmats-turbo/rMATS_P/FDR.py", line 45, in <module>
    ifile=open(sys.argv[1]);title=ifile.readline();
FileNotFoundError: [Errno 2] No such file or directory: '/media/nus/AMLab_Ext1/Shen/splicing/try/temp_output/JCEC_A3SS/rMATS_result_P-V.txt'
paste: /media/nus/AMLab_Ext1/Shen/splicing/try/temp_output/JCEC_A3SS/rMATS_result_FDR.txt: No such file or directory
/home/nus/Desktop/NGS/rmats-turbo/rMATS_C/rMATSexe: error while loading shared libraries: libgsl.so.23: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/home/nus/Desktop/NGS/rmats-turbo/rMATS_P/FDR.py", line 45, in <module>
    ifile=open(sys.argv[1]);title=ifile.readline();
FileNotFoundError: [Errno 2] No such file or directory: '/media/nus/AMLab_Ext1/Shen/splicing/try/temp_output/JC_A5SS/rMATS_result_P-V.txt'
paste: /media/nus/AMLab_Ext1/Shen/splicing/try/temp_output/JC_A5SS/rMATS_result_FDR.txt: No such file or directory
/home/nus/Desktop/NGS/rmats-turbo/rMATS_C/rMATSexe: error while loading shared libraries: libgsl.so.23: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/home/nus/Desktop/NGS/rmats-turbo/rMATS_P/FDR.py", line 45, in <module>
    ifile=open(sys.argv[1]);title=ifile.readline();
FileNotFoundError: [Errno 2] No such file or directory: '/media/nus/AMLab_Ext1/Shen/splicing/try/temp_output/JCEC_A5SS/rMATS_result_P-V.txt'
paste: /media/nus/AMLab_Ext1/Shen/splicing/try/temp_output/JCEC_A5SS/rMATS_result_FDR.txt: No such file or directory
/home/nus/Desktop/NGS/rmats-turbo/rMATS_C/rMATSexe: error while loading shared libraries: libgsl.so.23: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/home/nus/Desktop/NGS/rmats-turbo/rMATS_P/FDR.py", line 45, in <module>
    ifile=open(sys.argv[1]);title=ifile.readline();
FileNotFoundError: [Errno 2] No such file or directory: '/media/nus/AMLab_Ext1/Shen/splicing/try/temp_output/JC_RI/rMATS_result_P-V.txt'
paste: /media/nus/AMLab_Ext1/Shen/splicing/try/temp_output/JC_RI/rMATS_result_FDR.txt: No such file or directory
/home/nus/Desktop/NGS/rmats-turbo/rMATS_C/rMATSexe: error while loading shared libraries: libgsl.so.23: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/home/nus/Desktop/NGS/rmats-turbo/rMATS_P/FDR.py", line 45, in <module>
    ifile=open(sys.argv[1]);title=ifile.readline();
FileNotFoundError: [Errno 2] No such file or directory: '/media/nus/AMLab_Ext1/Shen/splicing/try/temp_output/JCEC_RI/rMATS_result_P-V.txt'
paste: /media/nus/AMLab_Ext1/Shen/splicing/try/temp_output/JCEC_RI/rMATS_result_FDR.txt: No such file or directory
Done processing count files.
```

**Comment by treepoplar** [comment]
I have the same issue.

**Comment by EricKutschera** [comment]
That error message is similar to the one from this: https://groups.google.com/g/rmats-user-group/c/S1GFEqB9TE8/m/YV9R27CoCwAJ

You could try following those instructions to reinstall rmats so that it looks for an available version of libgsl

**Comment by ShenTTT** [comment]
> That error message is similar to the one from this: https://groups.google.com/g/rmats-user-group/c/S1GFEqB9TE8/m/YV9R27CoCwAJ
> 
> You could try following those instructions to reinstall rmats so that it looks for an available version of libgsl

I saw this before but none of the method worked. I tried to install using conda but new errors popped up...
What I tried in the end was to simply copy the libgsl (so.19) in my system as the one expected by rmats (so.23):
`sudo cp /usr/lib/x86_64-linux-gnu/libgsl.so.19 /usr/lib/x86_64-linux-gnu/libgsl.so.23`
And I think it worked.

**Comment by ShenTTT** [comment]
I tried again using bioconda, still didnt work:
```
(base) nus@nus-H8QG7:~$ conda install -c conda-forge -c bioconda rmats=4.1.0
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: / 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
Examining conflict for arrow-cpp numpydoc chardet sphinxcontrib simplegeneric| ^failed 
```
Now I have no idea how I can install/run the program properly...

**Comment by ShenTTT** [comment]
An update: I rebuilt the program again and it worked using `./build_rmats --no-paired-model`, and command:
`python /home/nus/Desktop/NGS/rmats-turbo/rmats.py --b1 '/media/nus/AMLab_Ext1/Shen/splicing/try/Wr60_DS.txt' --b2 '/media/nus/AMLab_Ext1/Shen/splicing/try/Wr60_WS.txt' --gtf '/media/nus/AMLab_Ext1/Shen/splicing/try/converted.gtf' -t single --readLength 150 --variable-read-length --nthread 12 --tstat 1 --novelSS --od '/media/nus/AMLab_Ext1/Shen/splicing/try/output' --tmp '/media/nus/AMLab_Ext1/Shen/splicing/try/temp_output'`
 I changed nothing but it worked well, probably something went wrong during my first installation
